<?php

/**
 * @file
 * react_paragraphs.module
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_theme().
 */
function react_paragraphs_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['paragraphs_row'] = [
    'render element' => 'elements',
    'file' => 'paragraphs_row.page.inc',
    'template' => 'paragraphs_row',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function react_paragraphs_theme_suggestions_field(array $variables) {
  $suggestions = [];
  if (
    $variables['element']['#entity_type'] == 'paragraphs_row' &&
    $variables['element']['#field_type'] == 'entity_reference_revisions'
  ) {
    $suggestions[] = 'field__react_paragraphs_row';
  }
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function react_paragraphs_preprocess_field__react_paragraphs_row(&$variables) {
  $variables['attributes']['class'][] = 'react-paragraphs-row ';
  $variables['#attached']['library'][] = 'react_paragraphs/field_formatter';

  foreach ($variables['items'] as &$item) {
    /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
    $paragraph = $item['content']['#paragraph'];
    $width = $paragraph->getBehaviorSetting('react', 'width');
    $item['attributes']['data-react-columns'] = $width;
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function react_paragraphs_theme_suggestions_paragraphs_row(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#paragraphs_row'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'paragraphs_row__' . $sanitized_view_mode;
  $suggestions[] = 'paragraphs_row__' . $entity->bundle();
  $suggestions[] = 'paragraphs_row__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'paragraphs_row__' . $entity->id();
  $suggestions[] = 'paragraphs_row__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
