react_paragraphs.paragraphs_row_type.*:
  type: config_entity
  label: 'Paragraphs Row type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
