react_paragraphs.paragraphs_row_type.*:
  type: config_entity
  label: 'Paragraphs Row type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    behavior_plugins:
      type: sequence
      label: 'Plugins'
      orderby: key
      sequence:
        type: paragraphs.behavior.settings.[%key]
        label: 'Behavior plugins'
